version: '3.9'

services:
  database:
    image: mysql:8.0
    restart: always
    env_file:
      - .env
    volumes:
      - guest-note-app-db-data:/var/lib/mysql
    ports:
      - '3306:3306'

  backend:
    build:
      context: .
      dockerfile: ${DOCKERFILE}
    volumes:
      - .:/app
    ports:
      - '8080:8080'
    environment:
      NODE_ENV: development
      DATABASE_URL: "mysql://${DB_USER}:${DB_PASSWORD}@database:${DB_PORT}/${DB_NAME}"
    env_file:
      - .env
    depends_on:
      - database

volumes:
  guest-note-app-db-data:
