version: '3.9'

services:
  guest-note-app-database:
    image: mysql:8.0
    restart: always
    env_file:
      - .env
    volumes:
      - guest-note-app-db-data:/var/lib/mysql
    ports:
      - '3306:3306'

  guest-note-app-backend:
    build:
      context: .
      dockerfile: ${DOCKERFILE}
    volumes:
      - .:/app
    ports:
      - '8080:8080'
    environment:
      NODE_ENV: development
    env_file:
      - .env
    depends_on:
      - guest-note-app-database

volumes:
  guest-note-app-db-data:
